Samples/Application/Controllers/ListController.cs
using System;
using Application.Models.Forms;
using Application.Models.ViewModels;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using RegionOrebroLan.Web.Paging;

namespace Application.Controllers
{
	public class ListController : SiteController
	{
		#region Constructors

		public ListController(IPaginationFactory paginationFactory)
		{
			this.PaginationFactory = paginationFactory ?? throw new ArgumentNullException(nameof(paginationFactory));
		}

		#endregion

		#region Properties

		protected internal virtual IPaginationFactory PaginationFactory { get; }

		#endregion

		#region Methods

		public virtual IActionResult Index(PaginationSettingsForm form)
		{
			if(form == null)
				throw new ArgumentNullException(nameof(form));

			var url = new Uri(this.Request.GetDisplayUrl());

			var model = new ListViewModel
			{
				Form = form,
				Pagination = this.PaginationFactory.Create(form.MaximumNumberOfDisplayedPages, form.NumberOfItems, "PageIndex", form.PageSize, url, form.ZeroBasedIndex)
			};

			for(var i = 0; i < form.NumberOfItems; i++)
			{
				var index = i + (form.ZeroBasedIndex ? 0 : 1);

				model.Items.Add("Item-" + index);
			}

			return this.View(model);
		}

		#endregion
	}
}

Samples/Application/Controllers/RecaptchaController.cs
using Application.Models.Forms;
using Application.Models.ViewModels;
using Application.Models.Web.Mvc;
using Microsoft.AspNetCore.Mvc;

namespace Application.Controllers
{
	public class RecaptchaController : SiteController
	{
		#region Methods

		protected internal virtual RecaptchaViewModel CreateModel()
		{
			return this.CreateModel(null);
		}

		protected internal virtual RecaptchaViewModel CreateModel(RecaptchaForm form)
		{
			var model = new RecaptchaViewModel();

			if(form != null)
				model.Form = form;

			return model;
		}

		public virtual IActionResult Index()
		{
			return this.View(this.CreateModel());
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[ValidateRecaptchaToken]
		public virtual IActionResult Post(RecaptchaForm form)
		{
			var model = this.CreateModel(form);

			// ReSharper disable InvertIf
			if(this.ModelState.IsValid)
			{
				this.ModelState.Clear();
				model.Saved = true;
				model.Form = new RecaptchaForm();
			}
			// ReSharper restore InvertIf

			return this.View("Index", model);
		}

		#endregion
	}
}

Samples/Application/Views/Shared/Pagination.cshtml
@model IPagination
@if(Model != null && Model.Pages.Any())
{
	<ul class="pagination">
		<!-- First -->
		@if(Model.FirstPageUrl == null)
		{
			<li class="page-item disabled">
				<span class="page-link">&#x21E4;</span>
			</li>
		}
		else
		{
			<li class="page-item">
				<a class="page-link" href="@Model.FirstPageUrl.PathAndQueryAndFragment()" title="First">&#x21E4;</a>
			</li>
		}
		<!-- Previous -->
		@if(Model.PreviousPageUrl == null)
		{
			<li class="page-item disabled">
				<span class="page-link">&laquo;</span>
			</li>
		}
		else
		{
			<li class="page-item">
				<a class="page-link" href="@Model.PreviousPageUrl.PathAndQueryAndFragment()" title="Previous">&laquo;</a>
			</li>
		}
		@if(Model.Pages.Count() < Model.TotalNumberOfPages)
		{
			<!-- Previous group -->
			if(Model.PreviousPageGroupUrl == null)
			{
				<li class="page-item disabled">
					<span class="page-link">...</span>
				</li>
			}
			else
			{
				<li class="page-item">
					<a class="page-link" href="@Model.PreviousPageGroupUrl.PathAndQueryAndFragment()" title="Previous group">...</a>
				</li>
			}
		}
		<!-- Pages -->
		@foreach(var page in Model.Pages)
		{
			if(page.Selected)
			{
				<li class="page-item active">
					<a class="page-link" href="@(page.Url.PathAndQueryAndFragment())">@(page.Index)</a>
				</li>
			}
			else
			{
				<li class="page-item">
					<a class="page-link" href="@(page.Url.PathAndQueryAndFragment())">@(page.Index)</a>
				</li>
			}
		}
		@if(Model.Pages.Count() < Model.TotalNumberOfPages)
		{
			<!-- Next group -->
			if(Model.NextPageGroupUrl == null)
			{
				<li class="page-item disabled">
					<span class="page-link">...</span>
				</li>
			}
			else
			{
				<li class="page-item">
					<a class="page-link" href="@Model.NextPageGroupUrl.PathAndQueryAndFragment()" title="Next group">...</a>
				</li>
			}
		}
		<!-- Next -->
		@if(Model.NextPageUrl == null)
		{
			<li class="page-item disabled">
				<span class="page-link">&raquo;</span>
			</li>
		}
		else
		{
			<li class="page-item">
				<a class="page-link" href="@Model.NextPageUrl.PathAndQueryAndFragment()" title="Next">&raquo;</a>
			</li>
		}
		<!-- Last -->
		@if(Model.LastPageUrl == null)
		{
			<li class="page-item disabled">
				<span class="page-link">&#x21E5;</span>
			</li>
		}
		else
		{
			<li class="page-item">
				<a class="page-link" href="@Model.LastPageUrl.PathAndQueryAndFragment()" title="Last">&#x21E5;</a>
			</li>
		}
	</ul>
}

Samples/Application/Views/Shared/_Layout.cshtml
@{ ViewBag.Site = "Sample-application"; }
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>@ViewBag.Name | @ViewBag.Site</title>
		<link asp-append-version="true" href="~/Style/Site.min.css" rel="stylesheet" />
	</head>
	<body>
		<header>
			<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
				<div class="container-fluid">
					<a asp-action="Index" asp-controller="Home" class="navbar-brand">@ViewBag.Site</a>
					<button aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-bs-target="#navigation" data-bs-toggle="collapse" type="button">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse" id="navigation">
						<ul class="navbar-nav me-auto mb-2 mb-md-0">
							<li class="nav-item">
								<a asp-action="Index" asp-controller="List" class="nav-link@(Context.Request.Path.StartsWithSegments("/List") ? " active" : null)">List</a>
							</li>
							<li class="nav-item">
								<a asp-action="Index" asp-controller="Recaptcha" class="nav-link@(Context.Request.Path.StartsWithSegments("/Recaptcha") ? " active" : null)">Recaptcha</a>
							</li>
						</ul>
					</div>
				</div>
			</nav>
		</header>
		<main class="container pb-3" role="main">
			<h1>@ViewBag.Name</h1>
			@RenderBody()
		</main>
		<footer class="border-top container pt-1 text-center text-muted">
			&copy; 2021 - @ViewBag.Site
		</footer>
		@if(Recaptcha.Enabled)
		{
			<script
				data-recaptcha-configuration-error-message="reCAPTCHA configuration-error! This error-message could be localized."
				data-recaptcha-siteKey="@Recaptcha.SiteKey"
				data-recaptcha-tokenParameterName="@Recaptcha.TokenParameterName"
				id="recaptcha-script"
				src="@Recaptcha.ScriptUrl"></script>
		}
		<script asp-append-version="true" src="~/Scripts/Site.min.js"></script>
	</body>
</html>